import type { Metadata } from "next";
import "@styles/globals.css";
import { ThemeProvider } from "@/lib/themeProvider";

export const metadata: Metadata = {
  title: "Pomodoro App",
  description: "Generated by Devon Adams",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><ThemeProvider>{children}</ThemeProvider></body>
    </html>
  );
}
